# Generated by Django 2.0.3 on 2018-04-30 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('engine_capacity', models.FloatField(max_length=3)),
                ('body_type', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('lecinse_plate', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Car')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='FixationAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=4)),
                ('datetime', models.DateTimeField()),
                ('accident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Pedestrians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12)),
                ('fixated_accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.FixationAccident')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=100)),
                ('lecinse_number', models.CharField(max_length=9, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('fine', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='drivingviolation',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Violation'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='fixated_accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.FixationAccident'),
        ),
    ]
