# Generated by Django 2.0.3 on 2018-04-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lecinse_number',
        ),
    ]
