# Generated by Django 2.0.3 on 2018-04-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_remove_profile_lecinse_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car',
        ),
    ]
