# Generated by Django 2.0.3 on 2018-05-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_remove_profile_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingviolation',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drivingviolation',
            name='house',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='drivingviolation',
            name='street',
            field=models.CharField(default='Улица не указана', max_length=100),
        ),
    ]
