# Generated by Django 2.0.3 on 2018-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_auto_20180502_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixationaccident',
            name='accident_type',
        ),
        migrations.AddField(
            model_name='fixationaccident',
            name='accident_type',
            field=models.ManyToManyField(related_name='accident_type', to='appmain.Accident'),
        ),
    ]
