# Generated by Django 2.0.3 on 2018-05-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_auto_20180508_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingviolation',
            name='driver',
        ),
        migrations.AddField(
            model_name='drivingviolation',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appmain.Car'),
        ),
    ]
