# Generated by Django 2.0.5 on 2018-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0007_auto_20180510_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
