# Generated by Django 2.0.5 on 2018-05-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklama_in_efir',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sotrudnik_in_efir',
            name='id',
        ),
        migrations.AlterField(
            model_name='reklama_in_efir',
            name='id_efir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.Efir'),
        ),
        migrations.AlterField(
            model_name='reklama_in_efir',
            name='id_reklama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.Reklama'),
        ),
        migrations.AlterField(
            model_name='sotrudnik_in_efir',
            name='id_efir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.Efir'),
        ),
        migrations.AlterField(
            model_name='sotrudnik_in_efir',
            name='id_sotrudnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.Sotrudnik'),
        ),
    ]
