# Generated by Django 2.0.5 on 2018-05-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_sotrudnik_in_efir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sotrudnik_in_efir',
            old_name='efir',
            new_name='id_efir',
        ),
        migrations.RenameField(
            model_name='sotrudnik_in_efir',
            old_name='sotrudnik',
            new_name='id_sotrudnik',
        ),
    ]
